export type BookDefinition = {
  readonly id: string;
  readonly language: string;
  readonly title: string;
  readonly author: string;
  readonly gutenbergId?: number;
};

// New English entries are deliberately conservative: Project Gutenberg texts,
// English originals published no later than 1930, by authors who died by 1946.
export const BOOK_DEFINITIONS = [
  { id: "en-alice-wonderland", language: "en", title: "Alice’s Adventures in Wonderland", author: "Lewis Carroll" },
  { id: "en-jekyll-hyde", language: "en", title: "The Strange Case Of Dr. Jekyll And Mr. Hyde", author: "Robert Louis Stevenson" },
  { id: "en-call-wild", language: "en", title: "The Call of the Wild", author: "Jack London" },
  { id: "es-marianela", language: "es", title: "Marianela", author: "Benito Pérez Galdós" },
  { id: "de-alice-wonderland", language: "de", title: "Alice’s Abenteuer im Wunderland", author: "Lewis Carroll, Antonie Zimmermann" },
  { id: "fr-alice-wonderland", language: "fr", title: "Aventures D’Alice Au Pays Des Merveilles", author: "Lewis Carroll, Henri Bué" },
  { id: "en-pride-and-prejudice", language: "en", title: "Pride and Prejudice", author: "Jane Austen", gutenbergId: 1342 },
  { id: "en-sense-and-sensibility", language: "en", title: "Sense and Sensibility", author: "Jane Austen", gutenbergId: 161 },
  { id: "en-emma", language: "en", title: "Emma", author: "Jane Austen", gutenbergId: 158 },
  { id: "en-mansfield-park", language: "en", title: "Mansfield Park", author: "Jane Austen", gutenbergId: 141 },
  { id: "en-persuasion", language: "en", title: "Persuasion", author: "Jane Austen", gutenbergId: 105 },
  { id: "en-northanger-abbey", language: "en", title: "Northanger Abbey", author: "Jane Austen", gutenbergId: 121 },
  { id: "en-great-expectations", language: "en", title: "Great Expectations", author: "Charles Dickens", gutenbergId: 1400 },
  { id: "en-tale-of-two-cities", language: "en", title: "A Tale of Two Cities", author: "Charles Dickens", gutenbergId: 98 },
  { id: "en-oliver-twist", language: "en", title: "Oliver Twist", author: "Charles Dickens", gutenbergId: 730 },
  { id: "en-david-copperfield", language: "en", title: "David Copperfield", author: "Charles Dickens", gutenbergId: 766 },
  { id: "en-bleak-house", language: "en", title: "Bleak House", author: "Charles Dickens", gutenbergId: 1023 },
  { id: "en-hard-times", language: "en", title: "Hard Times", author: "Charles Dickens", gutenbergId: 786 },
  { id: "en-christmas-carol", language: "en", title: "A Christmas Carol", author: "Charles Dickens", gutenbergId: 46 },
  { id: "en-pickwick-papers", language: "en", title: "The Pickwick Papers", author: "Charles Dickens", gutenbergId: 580 },
  { id: "en-adventures-of-sherlock-holmes", language: "en", title: "The Adventures of Sherlock Holmes", author: "Arthur Conan Doyle", gutenbergId: 1661 },
  { id: "en-memoirs-of-sherlock-holmes", language: "en", title: "The Memoirs of Sherlock Holmes", author: "Arthur Conan Doyle", gutenbergId: 834 },
  { id: "en-return-of-sherlock-holmes", language: "en", title: "The Return of Sherlock Holmes", author: "Arthur Conan Doyle", gutenbergId: 108 },
  { id: "en-hound-of-the-baskervilles", language: "en", title: "The Hound of the Baskervilles", author: "Arthur Conan Doyle", gutenbergId: 2852 },
  { id: "en-study-in-scarlet", language: "en", title: "A Study in Scarlet", author: "Arthur Conan Doyle", gutenbergId: 244 },
  { id: "en-sign-of-the-four", language: "en", title: "The Sign of the Four", author: "Arthur Conan Doyle", gutenbergId: 2097 },
  { id: "en-valley-of-fear", language: "en", title: "The Valley of Fear", author: "Arthur Conan Doyle", gutenbergId: 3289 },
  { id: "en-lost-world", language: "en", title: "The Lost World", author: "Arthur Conan Doyle", gutenbergId: 139 },
  { id: "en-war-of-the-worlds", language: "en", title: "The War of the Worlds", author: "H. G. Wells", gutenbergId: 36 },
  { id: "en-time-machine", language: "en", title: "The Time Machine", author: "H. G. Wells", gutenbergId: 35 },
  { id: "en-invisible-man", language: "en", title: "The Invisible Man", author: "H. G. Wells", gutenbergId: 5230 },
  { id: "en-island-of-doctor-moreau", language: "en", title: "The Island of Doctor Moreau", author: "H. G. Wells", gutenbergId: 159 },
  { id: "en-first-men-in-the-moon", language: "en", title: "The First Men in the Moon", author: "H. G. Wells", gutenbergId: 1013 },
  { id: "en-dracula", language: "en", title: "Dracula", author: "Bram Stoker", gutenbergId: 345 },
  { id: "en-frankenstein", language: "en", title: "Frankenstein", author: "Mary Shelley", gutenbergId: 84 },
  { id: "en-treasure-island", language: "en", title: "Treasure Island", author: "Robert Louis Stevenson", gutenbergId: 120 },
  { id: "en-kidnapped", language: "en", title: "Kidnapped", author: "Robert Louis Stevenson", gutenbergId: 421 },
  { id: "en-black-arrow", language: "en", title: "The Black Arrow", author: "Robert Louis Stevenson", gutenbergId: 848 },
  { id: "en-master-of-ballantrae", language: "en", title: "The Master of Ballantrae", author: "Robert Louis Stevenson", gutenbergId: 864 },
  { id: "en-picture-of-dorian-gray", language: "en", title: "The Picture of Dorian Gray", author: "Oscar Wilde", gutenbergId: 174 },
  { id: "en-importance-of-being-earnest", language: "en", title: "The Importance of Being Earnest", author: "Oscar Wilde", gutenbergId: 844 },
  { id: "en-wonderful-wizard-of-oz", language: "en", title: "The Wonderful Wizard of Oz", author: "L. Frank Baum", gutenbergId: 55 },
  { id: "en-marvelous-land-of-oz", language: "en", title: "The Marvelous Land of Oz", author: "L. Frank Baum", gutenbergId: 54 },
  { id: "en-ozma-of-oz", language: "en", title: "Ozma of Oz", author: "L. Frank Baum", gutenbergId: 486 },
  { id: "en-dorothy-and-the-wizard-in-oz", language: "en", title: "Dorothy and the Wizard in Oz", author: "L. Frank Baum", gutenbergId: 420 },
  { id: "en-road-to-oz", language: "en", title: "The Road to Oz", author: "L. Frank Baum", gutenbergId: 485 },
  { id: "en-emerald-city-of-oz", language: "en", title: "The Emerald City of Oz", author: "L. Frank Baum", gutenbergId: 517 },
  { id: "en-little-women", language: "en", title: "Little Women", author: "Louisa May Alcott", gutenbergId: 514 },
  { id: "en-little-men", language: "en", title: "Little Men", author: "Louisa May Alcott", gutenbergId: 2788 },
  { id: "en-jos-boys", language: "en", title: "Jo’s Boys", author: "Louisa May Alcott", gutenbergId: 3499 },
  { id: "en-old-fashioned-girl", language: "en", title: "An Old-Fashioned Girl", author: "Louisa May Alcott", gutenbergId: 2787 },
  { id: "en-eight-cousins", language: "en", title: "Eight Cousins", author: "Louisa May Alcott", gutenbergId: 2726 },
  { id: "en-secret-garden", language: "en", title: "The Secret Garden", author: "Frances Hodgson Burnett", gutenbergId: 113 },
  { id: "en-little-princess", language: "en", title: "A Little Princess", author: "Frances Hodgson Burnett", gutenbergId: 146 },
  { id: "en-little-lord-fauntleroy", language: "en", title: "Little Lord Fauntleroy", author: "Frances Hodgson Burnett", gutenbergId: 479 },
  { id: "en-anne-of-green-gables", language: "en", title: "Anne of Green Gables", author: "L. M. Montgomery", gutenbergId: 45 },
  { id: "en-anne-of-avonlea", language: "en", title: "Anne of Avonlea", author: "L. M. Montgomery", gutenbergId: 47 },
  { id: "en-anne-of-the-island", language: "en", title: "Anne of the Island", author: "L. M. Montgomery", gutenbergId: 51 },
  { id: "en-rilla-of-ingleside", language: "en", title: "Rilla of Ingleside", author: "L. M. Montgomery", gutenbergId: 3796 },
  { id: "en-blue-castle", language: "en", title: "The Blue Castle", author: "L. M. Montgomery", gutenbergId: 67979 },
  { id: "en-adventures-of-tom-sawyer", language: "en", title: "The Adventures of Tom Sawyer", author: "Mark Twain", gutenbergId: 74 },
  { id: "en-adventures-of-huckleberry-finn", language: "en", title: "Adventures of Huckleberry Finn", author: "Mark Twain", gutenbergId: 76 },
  { id: "en-connecticut-yankee-in-king-arthurs-court", language: "en", title: "A Connecticut Yankee in King Arthur’s Court", author: "Mark Twain", gutenbergId: 86 },
  { id: "en-prince-and-the-pauper", language: "en", title: "The Prince and the Pauper", author: "Mark Twain", gutenbergId: 1837 },
  { id: "en-life-on-the-mississippi", language: "en", title: "Life on the Mississippi", author: "Mark Twain", gutenbergId: 245 },
  { id: "en-scarlet-letter", language: "en", title: "The Scarlet Letter", author: "Nathaniel Hawthorne", gutenbergId: 33 },
  { id: "en-house-of-the-seven-gables", language: "en", title: "The House of the Seven Gables", author: "Nathaniel Hawthorne", gutenbergId: 77 },
  { id: "en-moby-dick-or-the-whale", language: "en", title: "Moby-Dick; or, The Whale", author: "Herman Melville", gutenbergId: 2701 },
  { id: "en-typee", language: "en", title: "Typee", author: "Herman Melville", gutenbergId: 1900 },
  { id: "en-turn-of-the-screw", language: "en", title: "The Turn of the Screw", author: "Henry James", gutenbergId: 209 },
  { id: "en-ambassadors", language: "en", title: "The Ambassadors", author: "Henry James", gutenbergId: 432 },
  { id: "en-heart-of-darkness", language: "en", title: "Heart of Darkness", author: "Joseph Conrad", gutenbergId: 219 },
  { id: "en-lord-jim", language: "en", title: "Lord Jim", author: "Joseph Conrad", gutenbergId: 5658 },
  { id: "en-nostromo", language: "en", title: "Nostromo", author: "Joseph Conrad", gutenbergId: 2021 },
  { id: "en-secret-agent", language: "en", title: "The Secret Agent", author: "Joseph Conrad", gutenbergId: 974 },
  { id: "en-jungle-book", language: "en", title: "The Jungle Book", author: "Rudyard Kipling", gutenbergId: 236 },
  { id: "en-second-jungle-book", language: "en", title: "The Second Jungle Book", author: "Rudyard Kipling", gutenbergId: 1937 },
  { id: "en-kim", language: "en", title: "Kim", author: "Rudyard Kipling", gutenbergId: 2226 },
  { id: "en-captains-courageous", language: "en", title: "Captains Courageous", author: "Rudyard Kipling", gutenbergId: 2186 },
  { id: "en-just-so-stories", language: "en", title: "Just So Stories", author: "Rudyard Kipling", gutenbergId: 2781 },
  { id: "en-man-who-was-thursday", language: "en", title: "The Man Who Was Thursday", author: "G. K. Chesterton", gutenbergId: 1695 },
  { id: "en-innocence-of-father-brown", language: "en", title: "The Innocence of Father Brown", author: "G. K. Chesterton", gutenbergId: 204 },
  { id: "en-wisdom-of-father-brown", language: "en", title: "The Wisdom of Father Brown", author: "G. K. Chesterton", gutenbergId: 223 },
  { id: "en-ball-and-the-cross", language: "en", title: "The Ball and the Cross", author: "G. K. Chesterton", gutenbergId: 5265 },
  { id: "en-napoleon-of-notting-hill", language: "en", title: "The Napoleon of Notting Hill", author: "G. K. Chesterton", gutenbergId: 20058 },
  { id: "en-great-gatsby", language: "en", title: "The Great Gatsby", author: "F. Scott Fitzgerald", gutenbergId: 64317 },
  { id: "en-this-side-of-paradise", language: "en", title: "This Side of Paradise", author: "F. Scott Fitzgerald", gutenbergId: 805 },
  { id: "en-beautiful-and-damned", language: "en", title: "The Beautiful and Damned", author: "F. Scott Fitzgerald", gutenbergId: 9830 },
  { id: "en-tales-of-the-jazz-age", language: "en", title: "Tales of the Jazz Age", author: "F. Scott Fitzgerald", gutenbergId: 6695 },
  { id: "en-house-of-mirth", language: "en", title: "The House of Mirth", author: "Edith Wharton", gutenbergId: 284 },
  { id: "en-age-of-innocence", language: "en", title: "The Age of Innocence", author: "Edith Wharton", gutenbergId: 541 },
  { id: "en-ethan-frome", language: "en", title: "Ethan Frome", author: "Edith Wharton", gutenbergId: 4517 },
  { id: "en-custom-of-the-country", language: "en", title: "The Custom of the Country", author: "Edith Wharton", gutenbergId: 11052 },
  { id: "en-jane-eyre", language: "en", title: "Jane Eyre", author: "Charlotte Brontë", gutenbergId: 1260 },
  { id: "en-wuthering-heights", language: "en", title: "Wuthering Heights", author: "Emily Brontë", gutenbergId: 768 },
  { id: "en-tenant-of-wildfell-hall", language: "en", title: "The Tenant of Wildfell Hall", author: "Anne Brontë", gutenbergId: 969 },
  { id: "en-agnes-grey", language: "en", title: "Agnes Grey", author: "Anne Brontë", gutenbergId: 767 },
  { id: "en-middlemarch", language: "en", title: "Middlemarch", author: "George Eliot", gutenbergId: 145 },
  { id: "en-silas-marner", language: "en", title: "Silas Marner", author: "George Eliot", gutenbergId: 550 },
  { id: "en-mill-on-the-floss", language: "en", title: "The Mill on the Floss", author: "George Eliot", gutenbergId: 6688 },
  { id: "en-daniel-deronda", language: "en", title: "Daniel Deronda", author: "George Eliot", gutenbergId: 7469 },
  { id: "en-north-and-south", language: "en", title: "North and South", author: "Elizabeth Gaskell", gutenbergId: 4276 },
  { id: "en-woman-in-white", language: "en", title: "The Woman in White", author: "Wilkie Collins", gutenbergId: 583 },
] as const satisfies readonly BookDefinition[];
