export type ChainRefs = {
  canvas: HTMLCanvasElement;
  replayCanvas: HTMLCanvasElement;
  rowsInput: HTMLInputElement;
  colsInput: HTMLInputElement;
  enemiesInput: HTMLInputElement;
  rowsValue: HTMLOutputElement;
  colsValue: HTMLOutputElement;
  enemiesValue: HTMLOutputElement;
  settingsButton: HTMLButtonElement;
  newGameButton: HTMLButtonElement;
  menuButton: HTMLButtonElement;
  resumeButton: HTMLButtonElement;
  quickButton: HTMLButtonElement;
  playAgainButton: HTMLButtonElement;
  resultMenuButton: HTMLButtonElement;
  statsBackButton: HTMLButtonElement;
  replayClose: HTMLButtonElement;
  replayPrev: HTMLButtonElement;
  replayPlay: HTMLButtonElement;
  replayNext: HTMLButtonElement;
  replayResume: HTMLButtonElement;
  statsButtons: HTMLButtonElement[];
  presets: HTMLButtonElement[];
  stage: HTMLElement;
  statusEl: HTMLElement;
  botStatus: HTMLElement;
  botStatusLabel: HTMLElement;
  botErrorDetail: HTMLElement;
  botRetryButton: HTMLButtonElement;
  turnEl: HTMLElement;
  youSwatch: HTMLElement;
  activeSwatch: HTMLElement;
  settingsPanel: HTMLElement;
  openingView: HTMLElement;
  gameView: HTMLElement;
  resumeCard: HTMLElement;
  resumeEyebrow: HTMLElement;
  resumeTitle: HTMLElement;
  resumeCopy: HTMLElement;
  resumeSpec: HTMLElement;
  resultPanel: HTMLElement;
  resultTitle: HTMLElement;
  resultCopy: HTMLElement;
  statsView: HTMLElement;
  statGames: HTMLElement;
  statWins: HTMLElement;
  statRate: HTMLElement;
  statLargest: HTMLElement;
  statRecent: HTMLElement;
  replayPanel: HTMLElement;
  replayTitle: HTMLElement;
  replayCopy: HTMLElement;
  replayStatus: HTMLOutputElement;
};

export const createChainRefs = () => {
  const refs = Object.create(null) as ChainRefs;
  refs.statsButtons = [];
  refs.presets = [];
  return refs;
};
