import { KeybrMark, WordleMark, WORDLE_WORDMARK_COLORS } from '../../shared/components/Brand.tsx';
import { ChainLiveMark } from '../../shared/components/ChainLogo.tsx';
import type { Entry } from '../data.ts';
import { SmartLink } from '../../shared/components/NavLink.tsx';
const external=(href:string)=>/^https?:/.test(href);
export function CompactList(props:{entries:Entry[]}){return <div class="compact-list">{props.entries.map(x=><SmartLink class="compact-row" href={x.href} target={external(x.href)?'_blank':undefined} rel={external(x.href)?'noopener noreferrer':undefined} data-copy-label={x.title}><span><span class="compact-name">{x.title}</span><span class="compact-note">{x.note}</span></span><span class="row-kind">{x.kind}</span><span class="arrow" aria-hidden="true">›</span></SmartLink>)}</div>}
function GameTitle(props:{index:number}){if(props.index===0)return <WordleMark text="WORDLE" colors={WORDLE_WORDMARK_COLORS} class="game-title game-wordle"/>;if(props.index===1)return <KeybrMark class="game-title game-keybr"/>;return <ChainLiveMark class="game-chain-live"/>}
export function GameCards(props:{entries:Entry[]}){return <div class="grid">{props.entries.map((x,i)=><SmartLink class={`card game-card-${i}`} href={x.href} data-copy-label={x.title}><div class="card-top"><GameTitle index={i}/><span class="arrow">›</span></div><div class="card-copy">{x.note}</div></SmartLink>)}</div>}
export function ProjectCards(props:{entries:Entry[]}){return <div class="project-grid">{props.entries.map(x=><SmartLink class="project" href={x.href} documentPreload={x.demo === true} target={external(x.href)?'_blank':undefined} rel={external(x.href)?'noopener noreferrer':undefined} data-copy-label={x.title}><div class="project-head"><span class="project-name">{x.title}</span><span class="lang">{x.tags?.[0]||''}</span></div><p>{x.note}</p><div class="metric">{(x.tags||[]).slice(1).join(' / ')}</div></SmartLink>)}</div>}
