import { AlarmClockCheck } from '../../../../ui-kit/components/lucide.tsx';
import { CircleAlert } from '../../../../ui-kit/components/lucide.tsx';
import { Maximize2 } from '../../../../ui-kit/components/lucide.tsx';
import { ChartNoAxesColumn } from '../../../../ui-kit/components/lucide.tsx';
import { CircleCheck } from '../../../../ui-kit/components/lucide.tsx';
import { X } from '../../../../ui-kit/components/lucide.tsx';
import { Settings } from '../../../../ui-kit/components/lucide.tsx';
import { Move } from '../../../../ui-kit/components/lucide.tsx';
import { Trash2 } from '../../../../ui-kit/components/lucide.tsx';
import { Download } from '../../../../ui-kit/components/lucide.tsx';
import { Smile } from '../../../../ui-kit/components/lucide.tsx';
import { Frown } from '../../../../ui-kit/components/lucide.tsx';
import { CircleHelp } from '../../../../ui-kit/components/lucide.tsx';
import { House } from '../../../../ui-kit/components/lucide.tsx';
import { Info } from '../../../../ui-kit/components/lucide.tsx';
import { CirclePlay } from '../../../../ui-kit/components/lucide.tsx';
import { Redo2 } from '../../../../ui-kit/components/lucide.tsx';
import { SkipForward } from '../../../../ui-kit/components/lucide.tsx';
import { SkipBack } from '../../../../ui-kit/components/lucide.tsx';
import { CircleStop } from '../../../../ui-kit/components/lucide.tsx';
import { SunMoon } from '../../../../ui-kit/components/lucide.tsx';
import { Trophy } from '../../../../ui-kit/components/lucide.tsx';
import { Undo2 } from '../../../../ui-kit/components/lucide.tsx';
import { Upload } from '../../../../ui-kit/components/lucide.tsx';

export const mdiAlarmCheck = AlarmClockCheck;
export const mdiAlertCircleOutline = CircleAlert;
export const mdiAspectRatio = Maximize2;
export const mdiChartBar = ChartNoAxesColumn;
export const mdiCheckCircle = CircleCheck;
export const mdiCheckCircleOutline = CircleCheck;
export const mdiClose = X;
export const mdiCog = Settings;
export const mdiCursorMove = Move;
export const mdiDeleteForever = Trash2;
export const mdiDownload = Download;
export const mdiEmoticonHappy = Smile;
export const mdiEmoticonSad = Frown;
export const mdiHelpCircleOutline = CircleHelp;
export const mdiHome = House;
export const mdiInformationOutline = Info;
export const mdiPlayCircleOutline = CirclePlay;
export const mdiRedo = Redo2;
export const mdiSkipNext = SkipForward;
export const mdiSkipPrevious = SkipBack;
export const mdiStopCircleOutline = CircleStop;
export const mdiThemeLightDark = SunMoon;
export const mdiTrophy = Trophy;
export const mdiUndo = Undo2;
export const mdiUpload = Upload;
