import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import AxeBuilder from '@axe-core/playwright';
process.env.TMPDIR = process.env.BROWSER_TMPDIR ?? resolve('.tmp/btmp');
const screenshotDir = process.env.SCREENSHOT_DIR ?? resolve('.tmp/screenshots');
mkdirSync(screenshotDir, {recursive: true});
mkdirSync('.tmp/solid-v2', {recursive: true});
mkdirSync(process.env.TMPDIR, { recursive: true });
const url = process.env.WORDLE_TEST_URL ?? 'http://127.0.0.1:4319/wordle.html';
const browser = await chromium.launch({ executablePath: process.env.BROWSER_EXECUTABLE ?? (existsSync('/usr/bin/brave') ? '/usr/bin/brave' : undefined), headless: true });
const diagnostics = [], checks = [], warningStacks = [], runtimeErrors = [];
const check = name => { checks.push(name); console.log('PASS', name); };
async function fresh(width = 1280) {
  const context = await browser.newContext({ viewport: { width, height: 900 }, serviceWorkers: 'block' });
  const page = await context.newPage();
  await page.addInitScript(() => {
    globalThis.wordleWarningStacks = [];
    Error.stackTraceLimit = 28;
    const warn = console.warn;
    console.warn = (...args) => {
      if (String(args[0]).includes('STRICT_READ') && globalThis.wordleWarningStacks.length < 30) globalThis.wordleWarningStacks.push({ message: String(args[0]), stack: new Error().stack });
      warn.apply(console, args);
    };
  });
  page.on('pageerror', error => runtimeErrors.push(error.stack));
  page.on('pageerror', error => diagnostics.push(error.stack));
  page.on('console', message => { if (['warning', 'error'].includes(message.type())) diagnostics.push(message.text()); });
  for (const name of ['site.css', 'shared-runtime.js', 'favicon.svg']) await page.route(`**/${name}`, route => route.fulfill({ body: readFileSync(`docs/${name}`), contentType: name.endsWith('.css') ? 'text/css' : name.endsWith('.js') ? 'text/javascript' : 'image/svg+xml' }));
  return { context, page };
}
const board = page => page.locator('.wordle-board');
const letters = page => board(page).locator('.wordle-cell-letter').allTextContents().then(chars => chars.join('').replaceAll(' ', '').toLowerCase());
const storage = page => page.evaluate(() => Object.fromEntries(Object.entries(localStorage).filter(([key]) => key.startsWith('game.wordle.')).map(([key, value]) => [key, JSON.parse(value)])));
try {
  const { context, page } = await fresh();
  await page.goto(url);
  await expect(page.getByRole('heading', { name: 'Pick a game.' })).toBeVisible();
  check('opening screen');
  await page.getByRole('button', { name: 'Choose date' }).click();
  await expect(page.getByRole('table')).toBeVisible();
  await page.keyboard.press('Escape');
  check('date picker opens and dismisses');
  await page.goto(`${url}?g=tt,a,0,6,6,0`);
  await expect(board(page)).toBeVisible();
  await board(page).click();
  await page.keyboard.type('planet');
  await expect.poll(() => letters(page)).toBe('planet');
  await page.reload();
  await expect.poll(() => letters(page)).toBe('planet');
  check('typed draft survives reload');
  await board(page).click();
  await page.keyboard.press('Escape');
  const key = page.getByRole('button', { name: 'A', exact: true });
  const handle = await key.elementHandle();
  const box = await key.boundingBox();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await expect.poll(() => letters(page)).toBe('a');
  assert.equal(await handle.evaluate(element => element.isConnected), true);
  await page.mouse.up();
  await expect(page.locator('.wordle-key-pressed')).toHaveCount(0);
  check('pointer keyboard retains its node and releases pressed state');
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await expect(page.getByRole('switch', { name: 'Fast Invalidate' })).toBeVisible();
  await page.getByText('Fast Invalidate', { exact: true }).click();
  await expect(page.getByRole('switch', { name: 'Fast Invalidate' })).not.toBeChecked();
  await expect.poll(() => letters(page)).toBe('a');
  const maxGuesses = page.getByRole('slider', { name: 'Max guesses' });
  await maxGuesses.focus();
  await page.keyboard.press('ArrowRight');
  await expect(maxGuesses).toHaveValue('7');
  check('switch and controlled slider update without discarding progress');
  await page.getByRole('button', { name: 'Reveal', exact: true }).click();
  await expect(page.locator('.result-dialog')).toBeVisible();
  const answer = (await page.locator('.result-answer').innerText()).toLowerCase();
  assert.equal(answer.length, 6);
  const saved = Object.values(await storage(page)).find(value => value.history);
  assert.equal(saved.done, 2);
  assert.deepEqual(saved.history.at(-1), [answer, 'bbbbbb']);
  check('reveal persists complete answer and mask');
  await page.screenshot({ path: resolve(screenshotDir, 'solid-v2-wordle-reveal-desktop.png'), fullPage: true });
  await page.evaluate(() => { Object.defineProperty(navigator, 'clipboard', {configurable: true, value: {writeText: async text => { globalThis.copiedWordleUrl = text; }}}); });
  await page.getByRole('button', { name: 'Share', exact: true }).click();
  const share = page.getByRole('dialog', {name: 'Share Wordle challenge', exact: true});
  await expect(share).toBeVisible();
  await expect(share.getByRole('slider', {name: 'Max guesses'})).toHaveValue('7');
  await share.getByRole('slider', {name: 'Max guesses'}).focus();
  await page.keyboard.press('ArrowRight');
  await expect(share.getByRole('slider', {name: 'Max guesses'})).toHaveValue('8');
  await share.getByRole('button', {name: 'Copy', exact: true}).click();
  await expect(share.getByRole('button', {name: 'Copied!', exact: true})).toBeVisible();
  const copied = await page.evaluate(() => globalThis.copiedWordleUrl);
  assert.equal(new URL(copied).searchParams.get('g').split(',')[4], '8');
  assert.equal((await storage(page))['game.wordle.settings.hard'].maxTries, 7);
  check('share settings are isolated and the generated link preserves their values');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Change mode', exact: true }).click({timeout: 2000});
  await expect(page.getByRole('heading', { name: 'Pick a game.' })).toBeVisible();
  await page.getByRole('button', { name: 'Statistics', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Statistics', exact: true })).toBeVisible();
  await expect(page.getByText('No statistics yet.')).toHaveCount(0);
  check('statistics load after completion and navigation');
  warningStacks.push(...await page.evaluate(() => globalThis.wordleWarningStacks));
  await context.close();
  const win = await fresh(390);
  await win.page.goto(`${url}?g=tt,a,0,6,6,0`);
  await expect(board(win.page)).toBeVisible();
  await board(win.page).click();
  await win.page.keyboard.type(answer);
  await win.page.keyboard.press('Enter');
  await expect(win.page.locator('.result-kicker')).toContainText('Solved');
  const won = Object.values(await storage(win.page)).find(value => value.history);
  assert.equal(won.done, 0);
  assert.deepEqual(won.history.at(-1), [answer, 'gggggg']);
  const width = await win.page.evaluate(() => ({ actual: document.documentElement.scrollWidth, available: innerWidth }));
  assert.ok(width.actual <= width.available, JSON.stringify(width));
  check('correct guess completes on mobile without horizontal overflow');
  await win.page.waitForFunction(() => document.getAnimations().every(animation => animation.playState !== 'running' || animation.effect?.getComputedTiming().iterations === Infinity));
  const dialogBox = await win.page.locator('.result-dialog').boundingBox();
  assert.ok(dialogBox.x >= 0 && dialogBox.x + dialogBox.width <= 390, JSON.stringify(dialogBox));
  await win.page.screenshot({ path: resolve(screenshotDir, 'solid-v2-wordle-win-mobile.png'), fullPage: true });
  await win.page.getByRole('button', { name: 'Change mode', exact: true }).click();
  await expect(win.page.getByRole('heading', { name: 'Pick a game.' })).toBeVisible();
  await expect(win.page.locator('.result-dialog')).toHaveCount(0);
  await win.page.waitForFunction(() => document.getAnimations().every(animation => animation.playState !== 'running' || animation.effect?.getComputedTiming().iterations === Infinity));
  const accessibility = await new AxeBuilder({ page: win.page }).analyze();
  writeFileSync('.tmp/solid-v2/wordle-accessibility.json', JSON.stringify(accessibility.violations, null, 2));
  assert.deepEqual(accessibility.violations.map(violation => ({ id: violation.id, impact: violation.impact })), []);
  check('mobile opening accessibility');
  await win.context.close();
  const loss = await fresh();
  await loss.page.goto(`${url}?g=tt,a,0,6,2,0`);
  await expect(board(loss.page)).toBeVisible();
  await board(loss.page).click();
  await loss.page.keyboard.type('zzzzzz'); await loss.page.keyboard.press('Enter');
  await loss.page.keyboard.type('zzzzzz'); await loss.page.keyboard.press('Enter');
  await expect(loss.page.locator('.result-kicker')).toContainText('Game over');
  const failed = Object.values(await storage(loss.page)).find(value => value.history);
  assert.equal(failed.done, 1); assert.equal(failed.history.length, 2);
  check('exhausted guesses complete exactly once');
  await loss.context.close();
  assert.deepEqual([...new Set(diagnostics.filter(message => message !== 'Service Worker registration blocked by Playwright'))], []);
  assert.deepEqual(runtimeErrors, []);
  check('no runtime exceptions or Solid diagnostics');
} finally { writeFileSync('.tmp/solid-v2/wordle-regression-results.json', JSON.stringify({ checks, diagnostics, runtimeErrors, warningStacks }, null, 2)); await browser.close(); }
